---

- name: install fonts
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - ttf-dejavu
    - ttf-liberation
    - ttf-droid
    - ttf-hack
    - noto-fonts-emoji
    - fontconfig
    - xorg-font-utils
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
