---

- name: install i3 windowmanager and components
  pacman:
    name:
      - xorg
      - xorg-server
      - xorg-xinit
      - i3-wm
      - i3lock
      - i3status
      - feh
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: create i3wm configuration directory
  file:
    name: /home/{{ user.name }}/.config/i3
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
